; Части APK приходят по 4 МБ; с запасом.
post_max_size = 16M
upload_max_filesize = 16M
memory_limit = 256M
expose_php = Off

opcache.enable = 1
opcache.validate_timestamps = 0
opcache.memory_consumption = 128
opcache.max_accelerated_files = 20000
realpath_cache_size = 4096K
realpath_cache_ttl = 600
